### PR TITLE
Yungong - UX fix, changing buy/sell into title case

### LINKED ISSUE #10: MINOR UX FIX: Inconsistent capitalization on Modal
When buying and selling cows, there's a modal that pops up:

image

image

The case is inconsistent.  `Cancel` is capitalized (Title Case) but `buy` is lowercase.

Make them both title case.

### PR DESCRIPTION
**Pull request by yungongWang**
## Overview

In this PR, when buying and selling cows, the text of buying and selling buttons are capitalized.
I only modify ManageCows.js, ManageCowsModal.js in frontend/Components, and ManageCows.test.js, ManageCowsModal.test.js. I do not know why so many files are changed. I also do not know why the GitHub stryker test kepp failing while the same test all passed on my local, which costed me so many times and made my progress a little behind, sorry about that. Maybe just ignored the other changed files and only view the ManageCows files? Thanks.
## Screenshots (Optional)

before:
image
after:
image
image

## Validation (Optional)

I deployed on my personal dev app:
https://happycows-dev-yungong.dokku-12.cs.ucsb.edu/

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #10

### CODE REVIEW

**Review by jzipkin1812 — DISMISSED** [review]
The changes to capitalization look good to me. I ran on the deployment and was able to verify. The checks are also passing, so we can merge this.

**Review by pconrad — CHANGES_REQUESTED** [review]
This needs to be fixed... there should only be four changed files here, not 453.

This thread on the Slack explains how to fix up this branch so that the 449 irrelevant files are not part of the commit:

https://ucsb-cs156-f24.slack.com/archives/C07PCA3GTBN/p1732221049948739

**Review by jzipkin1812 — APPROVED** [review]
I see that only the necessary files (and a github workflow that i don't think matters?) were changed, much better.

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
