### PR TITLE
Sort by leaderbord wealth bug fix

### LINKED ISSUE #12: BUG: Fix Leaderboard Sort by Total Wealth
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

We have noticed that the leaderboard incorrectly ranks Farmers when sorting by total wealth, under certain conditions.

### Expected Behavior

Clicking on the "Total Wealth" table column on the leaderboard should sort the Farmers from least to greatest wealth, and clicking it again should sort from greatest to least wealth. 

### Current / Observed Behavior

When a farmer has between $0 and $1000 (non inclusive), we notice that they are inaccurately sorted on the leaderboard.
Screenshot 2024-11-14 at 5 23 57 PM

Sorting from greatest to least should have put the first 2 farmers at the very bottom of the list, instead it puts them at the top.

We see this when sorting from least to greatest:
Screenshot 2024-11-14 at 5 24 17 PM

The farmers with $100 and $199 should have been ranked at the top of the leaderboard for having the least wealth, but they do not appear until the very bottom

### Steps to Reproduce

1. https://happycows.dokku-00.cs.ucsb.edu/
2. Navigate to the Testing Commons
3. Navigate to the leaderboard
4. Sort by Total Wealth

### Discussion

The issue is probably one related to sorting "strings" vs. sorting "numbers", and will involve having to understand internal details of the OurTable component.

Recognize that the OurTable component is used in many places in the application, so you need a solution that doesn't involve putting specific special case code into that component.

### PR DESCRIPTION
**Pull request by jzipkin1812**
## Overview
Fixes the bug where sorting by wealth on the leaderboard incorrectly ranks users with less than $1000 total wealth. 

## Screenshots (Optional)
As you can see, the sorting is working properly under the conditions described in the issue:
image
image

## Validation (Optional)

Run this branch and log in with 2 different accounts. Reduce one user's wealth below $1000 and sort the leaderboard by wealth.

## Deployment
I've logged in to two different accounts on this deployment in the commons called "test for sorting bug" to showcase that the leaderboard sorting works.
https://happycows-qa.dokku-12.cs.ucsb.edu/

## Linked Issues

Closes #12

### CODE REVIEW

**Review by pconrad — CHANGES_REQUESTED** [review]
Even though neither `npm run coverage` nor `npx stryker run` is demanding a test for this, it would still be good practice to add one.

That way, if there is a "regression", i.e. if someone changes the code in a way that reintroduces the bug, we'll know.

I'd suggest setting up data for wealth amounts $595 and $10000, just like in your PR description, then clicking the sort carets, and asserting that the numbers appear in the correct order.

The test should probably go in  LeaderboardTable.test.js but you can find some sample code that does something like what you want by looking in this test from `OurTable.test.js`:


```
test("click on a header and a sort caret should appear", async () => {
```

**Comment by jzipkin1812** [comment]
Added the requested test in leaderboardTable.test.js

**Review by mayarosenbaum — APPROVED** [review]
Looks good. Tested and everything seems to be working correctly.

**Review by pconrad — APPROVED** [review]
Code looks good, but I'd like to test on a dokku deployment before merging.

Could you deploy this and put a link to the dokku deployment on the description or in the comments?

**Comment by jzipkin1812** [comment]
> Code looks good, but I'd like to test on a dokku deployment before merging.
> 
> Could you deploy this and put a link to the dokku deployment on the description or in the comments?

I'm already using my personal dokku dev deployment for showcasing another PR, so is there an easy way to deploy this and not erase anyone else's deployment?

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
